services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik.rule=Host(`localhost`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.strip-dashboard.stripPrefix.prefixes=/dashboard"
      - "traefik.http.routers.traefik.middlewares=strip-dashboard"

#Implemetancion de RabbitMQ con su puerto para ver la interfaz de administración
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto para comunicación AMQP
      - "15672:15672" # Puerto para la interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  registro-app:
    build:
      context: ./registro-app
    labels:
      - "traefik.http.routers.registro.rule=Host(`localhost`) && PathPrefix(`/registro`)"
      - "traefik.http.routers.registro.entrypoints=web"
      - "traefik.http.routers.registro.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$dhfKKzDd$$1llfwmUPc7hQ3tbx3ypEw/"
      - "traefik.http.services.registro.loadbalancer.server.port=5000"

  cliente-uno:
    build:
      context: ./cliente-app
    environment:
      - SERVICE_ID=uno
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    labels:
      - "traefik.http.routers.uno.rule=Host(`localhost`) && PathPrefix(`/cliente/uno`)"
      - "traefik.http.middlewares.strip-uno.stripPrefix.prefixes=/cliente/uno"
      - "traefik.http.routers.uno.middlewares=strip-uno"
      - "traefik.http.services.uno.loadbalancer.server.port=5000"

  cliente-dos:
    build:
      context: ./cliente-app
    environment:
      - SERVICE_ID=dos
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    labels:
      - "traefik.http.routers.dos.rule=Host(`localhost`) && PathPrefix(`/cliente/dos`)"
      - "traefik.http.middlewares.strip-dos.stripPrefix.prefixes=/cliente/dos"
      - "traefik.http.routers.dos.middlewares=strip-dos"
      - "traefik.http.services.dos.loadbalancer.server.port=5000"

  monitor:
    build:
      context: ./monitor
    labels:
      - "traefik.http.routers.monitor.rule=Host(`localhost`) && PathPrefix(`/monitor`)"
      - "traefik.http.routers.monitor.entrypoints=web"
      - "traefik.http.middlewares.strip-monitor.stripPrefix.prefixes=/monitor"
      - "traefik.http.routers.monitor.middlewares=strip-monitor"
      - "traefik.http.services.monitor.loadbalancer.server.port=80"

  analytics-app:
    build:
      context: ./analytics-app
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy #HEALTHCHECK
    labels:
      - "traefik.enable=false" # Disable Traefik for this service as it's only a consumer